### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by NightMachinary** [webyrd/Barliman#27]
![image](https://user-images.githubusercontent.com/36224762/39100713-3d7d47b6-46a3-11e8-962c-5267b1917b56.png)

![image](https://user-images.githubusercontent.com/36224762/39100752-06c1d16e-46a4-11e8-8381-32bf90f3938d.png)

**Comment by gregr** [comment]
@NightMachinary , yes, unfortunately there's a large amount of Scheme that we don't support yet, including addition.  We do want to support this eventually, but don't have a time frame for when that will be.

For now, if you want to perform synthesis involving arithmetic, you'll have to encode numbers as list structures of some kind.  Peano numerals work well enough to handle simple cases.  Binary representations may be more efficient for normal execution, but I wouldn't be surprised if it made synthesis more difficult in some cases.
